#!/usr/bin/env bash
#that scripte prints 9 best school and 1 hi and another best school
A=0
while [ $A -lt 10 ];
   do
	echo "Best School"

	if [ $A -eq 8 ]
	then	
		echo "Best School"
		echo "Hi"
	fi
	A=$((A+1))
done
